title: VeRi Dataset
description: This is the project page for VeRi dataset which is a large scale image dataset for vehicle re-identification in urban traffic surveillance.
author: Xinchen Liu
theme: jekyll-theme-cayman
